version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - './demo/db:/srv/wasaphoto'
    environment:
      CFG_CONFIG_PATH: /etc/wasaphoto/config.yml

