services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - "./demo/db:/tmp/db"
    environment:
      CFG_CONFIG_PATH: /etc/wasaphoto/config.yml
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
