version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - './data/conf:/etc/wasaphoto'
      - './data/db:/srv/wasaphoto'
